version: '3'
services:
  db:
    image: postgres:13-alpine
    container_name: db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env.test
    command: postgres -p ${POSTGRES_PORT}

  node_app:
    container_name: node_app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:5000
    env_file:
      - .env.test
    depends_on:
      - db