name: Pull Request

on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
            POSTGRES_USERNAME: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            POSTGRES_DB: db_test
            DATABASE_URL: postgres://postgres:123456@db:5432/db_test?schema=public
            file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_app npm run test
      - name: Build
        run: npm i && npm run build
